package themes

import (
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/27te/winshell/internal/config"
)

//go:embed data/*.json
var themeFiles embed.FS

func List() []string {
	entries, _ := themeFiles.ReadDir("data")
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		name := strings.TrimSuffix(e.Name(), ".json")
		names = append(names, name)
	}
	return names
}

func Apply(name string) error {
	// Read theme JSON
	data, err := themeFiles.ReadFile(fmt.Sprintf("data/%s.json", name))
	if err != nil {
		return fmt.Errorf("theme file not found: %w", err)
	}

	// Parse theme
	theme, err := parseTheme(data)
	if err != nil {
		return fmt.Errorf("invalid theme file: %w", err)
	}

	// Apply WezTerm config
	if err := writeWezTerm(theme); err != nil {
		return fmt.Errorf("failed to apply WezTerm theme: %w", err)
	}
	fmt.Println("  ✓ WezTerm")

	// Apply Starship config
	if err := writeStarship(theme); err != nil {
		return fmt.Errorf("failed to apply Starship theme: %w", err)
	}
	fmt.Println("  ✓ Starship")

	// Apply FZF env in profile
	if err := writeFzfColors(theme); err != nil {
		return fmt.Errorf("failed to apply fzf theme: %w", err)
	}
	fmt.Println("  ✓ fzf")

	// Save current theme
	if err := saveCurrent(name); err != nil {
		fmt.Printf("  ⚠  Could not save current theme name: %v\n", err)
	}

	fmt.Printf("\n✓ Theme '%s' applied. Restart WezTerm to see changes.\n", name)
	return nil
}

func saveCurrent(name string) error {
	dir := filepath.Join(os.Getenv("USERPROFILE"), ".winshell")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "current_theme"), []byte(name), 0o644)
}

func GetCurrent() string {
	path := filepath.Join(os.Getenv("USERPROFILE"), ".winshell", "current_theme")
	data, err := os.ReadFile(path)
	if err != nil {
		return "none"
	}
	return string(data)
}

func writeWezTerm(t *Theme) error {
	content := fmt.Sprintf(`local wezterm = require "wezterm"
local act = wezterm.action
local config = wezterm.config_builder()

-- Shell
config.default_prog = { "pwsh.exe", "-NoLogo" }

-- GPU / Render
config.front_end = "WebGpu"
config.webgpu_power_preference = "HighPerformance"
config.animation_fps = 60
config.max_fps = 60
config.prefer_egl = true

-- Font
config.font = wezterm.font("JetBrains Mono", { weight = "Regular" })
config.font_size = 13.0
config.freetype_load_target = "Light"
config.freetype_render_target = "HorizontalLcd"

-- Theme: %s
config.color_scheme = "%s"
config.window_background_opacity = 0.97
config.text_background_opacity = 1.0
config.window_decorations = "RESIZE"
config.window_padding = { left = 12, right = 12, top = 8, bottom = 8 }

-- Tabs
config.enable_tab_bar = true
config.hide_tab_bar_if_only_one_tab = true
config.use_fancy_tab_bar = false
config.tab_bar_at_bottom = true
config.tab_max_width = 32

-- Performance
config.scrollback_lines = 5000
config.enable_scroll_bar = false
config.audible_bell = "Disabled"

-- Leader (Ctrl+b like tmux)
config.leader = { key = "b", mods = "CTRL", timeout_milliseconds = 1000 }

config.keys = {
  { key = "\\", mods = "LEADER", action = act.SplitHorizontal { domain = "CurrentPaneDomain" } },
  { key = "-",  mods = "LEADER", action = act.SplitVertical   { domain = "CurrentPaneDomain" } },
  { key = "h",  mods = "LEADER", action = act.ActivatePaneDirection "Left"  },
  { key = "l",  mods = "LEADER", action = act.ActivatePaneDirection "Right" },
  { key = "k",  mods = "LEADER", action = act.ActivatePaneDirection "Up"    },
  { key = "j",  mods = "LEADER", action = act.ActivatePaneDirection "Down"  },
  { key = "H",  mods = "LEADER", action = act.AdjustPaneSize { "Left",  5 } },
  { key = "L",  mods = "LEADER", action = act.AdjustPaneSize { "Right", 5 } },
  { key = "K",  mods = "LEADER", action = act.AdjustPaneSize { "Up",    5 } },
  { key = "J",  mods = "LEADER", action = act.AdjustPaneSize { "Down",  5 } },
  { key = "x",  mods = "LEADER", action = act.CloseCurrentPane { confirm = false } },
  { key = "c",  mods = "LEADER", action = act.SpawnTab "CurrentPaneDomain" },
  { key = "n",  mods = "LEADER", action = act.ActivateTabRelative(1)  },
  { key = "p",  mods = "LEADER", action = act.ActivateTabRelative(-1) },
  { key = "w",  mods = "LEADER", action = act.ShowTabNavigator },
  { key = "z",  mods = "LEADER", action = act.TogglePaneZoomState },
  { key = "[",  mods = "LEADER", action = act.ActivateCopyMode },
  { key = "r",  mods = "LEADER", action = act.ReloadConfiguration },
}

return config
`, t.Name, t.WezTerm.ColorScheme)

	return os.WriteFile(config.WezTermPath(), []byte(content), 0o644)
}

func writeStarship(t *Theme) error {
	content := fmt.Sprintf(`# WinShell theme: %s
# Generated by winshell — do not edit manually

palette = "%s"

[palettes.%s]
%s

[character]
success_symbol = "[❯](bold fg:%s)"
error_symbol = "[❯](bold red)"

[directory]
style = "bold fg:%s"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "bold fg:%s"

[git_status]
style = "fg:%s"

[nodejs]
symbol = " "
style = "bold fg:%s"

[python]
symbol = " "
style = "bold fg:%s"

[golang]
symbol = " "
style = "bold fg:%s"
`, t.Name, t.Name, t.Name, t.Starship.Palette,
		t.Starship.PromptColor,
		t.Starship.DirColor,
		t.Starship.BranchColor,
		t.Starship.StatusColor,
		t.Starship.NodeColor,
		t.Starship.PythonColor,
		t.Starship.GoColor,
	)

	path := config.StarshipPath()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func writeFzfColors(t *Theme) error {
	// Read current profile
	profilePath := config.PowerShellProfilePath()
	data, err := os.ReadFile(profilePath)
	if err != nil {
		return fmt.Errorf("could not read profile: %w", err)
	}

	// Replace FZF_DEFAULT_OPTS block
	lines := strings.Split(string(data), "\n")
	newLines := []string{}
	skip := false

	for _, line := range lines {
		if strings.Contains(line, "$env:FZF_DEFAULT_OPTS") {
			skip = true
		}
		if skip && strings.Contains(line, "--preview-window=right") {
			skip = false
			// Write new fzf opts
			newLines = append(newLines, fmt.Sprintf(`$env:FZF_DEFAULT_OPTS="%s"`, t.Fzf.Opts))
			continue
		}
		if !skip {
			newLines = append(newLines, line)
		}
	}

	return os.WriteFile(profilePath, []byte(strings.Join(newLines, "\n")), 0o644)
}
